version: "3.9"

services:

  service-mongodb:
    container_name: container-mongodb
    image: mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - .docker/db-mongo:/data/db
      - .docker/db-mongo-log:/log
    ports:
      - "27017:27017"
    networks:
      - network

volumes:
  .docker:

networks:
  network: { }
  